version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-pipeline-lab-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-loet7lavlwzf"
s3_prefix = "sam-pipeline-lab-app"
region = "sa-east-1"
profile = "clanmetalceara"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
